"""add bounties and submissions tables

Revision ID: 769e7dbf88bf
Revises: 146282ed91e2
Create Date: 2026-03-17 08:43:35.567412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769e7dbf88bf'
down_revision: Union[str, Sequence[str], None] = '146282ed91e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_node_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reward_tck', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escrow_reference', sa.String(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('winner_node_id', sa.String(), nullable=True),
    sa.Column('winner_submission_id', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_category'), 'bounties', ['category'], unique=False)
    op.create_index(op.f('ix_bounties_created_at'), 'bounties', ['created_at'], unique=False)
    op.create_index(op.f('ix_bounties_creator_node_id'), 'bounties', ['creator_node_id'], unique=False)
    op.create_index(op.f('ix_bounties_deadline_at'), 'bounties', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_bounties_status'), 'bounties', ['status'], unique=False)
    op.create_table('bounty_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bounty_id', sa.String(), nullable=False),
    sa.Column('solver_node_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.ForeignKeyConstraint(['solver_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounty_submissions_bounty_id'), 'bounty_submissions', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_created_at'), 'bounty_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_solver_node_id'), 'bounty_submissions', ['solver_node_id'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_status'), 'bounty_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounty_submissions_status'), table_name='bounty_submissions')
    op.drop_index(op.f('ix_bounty_submissions_solver_node_id'), table_name='bounty_submissions')
    op.drop_index(op.f('ix_bounty_submissions_created_at'), table_name='bounty_submissions')
    op.drop_index(op.f('ix_bounty_submissions_bounty_id'), table_name='bounty_submissions')
    op.drop_table('bounty_submissions')
    op.drop_index(op.f('ix_bounties_status'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_deadline_at'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_creator_node_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_created_at'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_category'), table_name='bounties')
    op.drop_table('bounties')
    # ### end Alembic commands ###
