"""initial schema

Revision ID: dd162cfbe5bc
Revises: 
Create Date: 2026-03-16 18:46:00.617557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd162cfbe5bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_access_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signup_token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('primary_capability', sa.String(length=100), nullable=True),
    sa.Column('why_joining', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('linked_node_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_access_signups_email'), 'early_access_signups', ['email'], unique=False)
    op.create_index(op.f('ix_early_access_signups_id'), 'early_access_signups', ['id'], unique=False)
    op.create_index(op.f('ix_early_access_signups_signup_token'), 'early_access_signups', ['signup_token'], unique=True)
    op.create_index(op.f('ix_early_access_signups_status'), 'early_access_signups', ['status'], unique=False)
    op.create_table('genesis_badge_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('genesis_rank', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('first_tx_id', sa.String(length=100), nullable=True),
    sa.Column('badge_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genesis_badge_awards_awarded_at'), 'genesis_badge_awards', ['awarded_at'], unique=False)
    op.create_index(op.f('ix_genesis_badge_awards_genesis_rank'), 'genesis_badge_awards', ['genesis_rank'], unique=False)
    op.create_index(op.f('ix_genesis_badge_awards_id'), 'genesis_badge_awards', ['id'], unique=False)
    op.create_index(op.f('ix_genesis_badge_awards_node_id'), 'genesis_badge_awards', ['node_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_skill_id'), 'jobs', ['skill_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cri_score', sa.Float(), nullable=True),
    sa.Column('cri_updated_at', sa.DateTime(), nullable=True),
    sa.Column('signup_token', sa.String(length=64), nullable=True),
    sa.Column('has_genesis_badge', sa.Boolean(), nullable=True),
    sa.Column('genesis_rank', sa.Integer(), nullable=True),
    sa.Column('first_settled_tx_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_api_key_hash'), 'nodes', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_nodes_fingerprint'), 'nodes', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_nodes_genesis_rank'), 'nodes', ['genesis_rank'], unique=False)
    op.create_index(op.f('ix_nodes_has_genesis_badge'), 'nodes', ['has_genesis_badge'], unique=False)
    op.create_index(op.f('ix_nodes_ip_address'), 'nodes', ['ip_address'], unique=False)
    op.create_index(op.f('ix_nodes_signup_token'), 'nodes', ['signup_token'], unique=False)
    op.create_table('pending_challenges',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expected_solution', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('escrows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proof_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('auto_settle_at', sa.DateTime(), nullable=True),
    sa.Column('auto_refund_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrows_auto_refund_at'), 'escrows', ['auto_refund_at'], unique=False)
    op.create_index(op.f('ix_escrows_auto_settle_at'), 'escrows', ['auto_settle_at'], unique=False)
    op.create_index(op.f('ix_escrows_buyer_id'), 'escrows', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_escrows_created_at'), 'escrows', ['created_at'], unique=False)
    op.create_index(op.f('ix_escrows_seller_id'), 'escrows', ['seller_id'], unique=False)
    op.create_index(op.f('ix_escrows_status'), 'escrows', ['status'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('price_tck', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('escrow_id', sa.String(), nullable=True),
    sa.Column('integration', sa.String(), nullable=True),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_buyer_id'), 'tasks', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_seller_id'), 'tasks', ['seller_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_seller_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_buyer_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('skills')
    op.drop_index(op.f('ix_escrows_status'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_seller_id'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_created_at'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_buyer_id'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_auto_settle_at'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_auto_refund_at'), table_name='escrows')
    op.drop_table('escrows')
    op.drop_table('pending_challenges')
    op.drop_index(op.f('ix_nodes_signup_token'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_ip_address'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_has_genesis_badge'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_genesis_rank'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_fingerprint'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_api_key_hash'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_jobs_skill_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_genesis_badge_awards_node_id'), table_name='genesis_badge_awards')
    op.drop_index(op.f('ix_genesis_badge_awards_id'), table_name='genesis_badge_awards')
    op.drop_index(op.f('ix_genesis_badge_awards_genesis_rank'), table_name='genesis_badge_awards')
    op.drop_index(op.f('ix_genesis_badge_awards_awarded_at'), table_name='genesis_badge_awards')
    op.drop_table('genesis_badge_awards')
    op.drop_index(op.f('ix_early_access_signups_status'), table_name='early_access_signups')
    op.drop_index(op.f('ix_early_access_signups_signup_token'), table_name='early_access_signups')
    op.drop_index(op.f('ix_early_access_signups_id'), table_name='early_access_signups')
    op.drop_index(op.f('ix_early_access_signups_email'), table_name='early_access_signups')
    op.drop_table('early_access_signups')
    # ### end Alembic commands ###
